### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by Zibri** [devilsclaw/flasher#1]
Ubuntu 16.10.

git clone https://github.com/devilsclaw/flasher.git
cd flasher
cmake -P prebuild.cmake
cmake -P build.cmake
make clean
make

/build/bin/flasher/flasher -D (Or any other command)
Devilsclaw's LG Renesas Drive Utility
cmd_drive: Opening Drive: /dev/sg0.
Segmentation fault (core dumped)

tried /dev/cdrom /dev/dvdrw /dev/sg0 /dev/sr0   same result.

**Comment by Zibri** [comment]
Help.. still the same problem after 2 years :(

**Comment by devilsclaw** [comment]
first off you must be in the same directory as the flasher

cd /build/bin/flasher/

second you must have root privs

sudo ./flasher -D /dev/sg0
