### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by benjamin-wilson** [devilsclaw/flasher#6]
Pop! 20.10

![image](https://user-images.githubusercontent.com/1399163/116786119-078f8180-aa6b-11eb-9340-094b4ba11911.png)

```
git clone https://github.com/devilsclaw/flasher.git
cd flasher
cmake .
make

```

$ sudo ./flasher -d /dev/sr0 -m main_firmware.bin
```
Devilsclaw's LG Renesas Drive Utility
cmd_drive: Opening Drive: /dev/sr0.
Segmentation fault
```

**Comment by devilsclaw** [comment]
This is due to the fact that the pointer type is 32bit on a 64bit system, just fix the pointer type and it should work. At some point I should fix this my self, I just don't have any rom drives in any of my systems anymore.

**Comment by dribgnikcom** [comment]
Can we get a new Windows binary please with the updated commits that add header recognition for newer drives please?  I am trying to cross-flash my OEM GH70N.  If not I'll try to do it on Linux.
